version: '3.1'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: timescaledb
      POSTGRES_PASSWORD: password
    volumes:
      - ./timescaledb-data:/var/lib/postgresql/data
