version: '3.1'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USERNAME:-timescaledb}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - ./.data:/var/lib/postgresql/data
